### ISSUE TITLE
Compiling python fails due to missing NSGAPopulation.h

### ISSUE THREAD

**Issue by PureW** [peter-ch/MultiNEAT#12]
NSGAPopulation.h was commented out in Main.cpp but not in PythonBindings.h. This seems to cause error during python-bindings compilation.

> In file included from src/PythonBindings.cpp:8:0:
> src/PythonBindings.h:42:28: fatal error: NSGAPopulation.h: No such file or directory
>  #include "NSGAPopulation.h"

Removing the include from PythonBindings.h fixes this error.

**Comment by peter-ch** [comment]
Thanks, that is fixed.
