### ISSUE TITLE
Example code crashes

### ISSUE THREAD

**Issue by iver56** [peter-ch/MultiNEAT#16]
When I run the code at http://multineat.com/docs.html I get the following error:

```
ArgumentError: Python argument types in
    Population.__init__(Population, Genome, Parameters, bool, float)
did not match C++ signature:
    __init__(struct _object *, char *)
    __init__(struct _object *, class NEAT::Genome, class NEAT::Parameters, bool, double, int)
```

The culprit is `pop = NEAT.Population(genome, params, True, 1.0)`. It seems that I have to add another argument for it to work. A seed for a pseudo-random number generator, perhaps? I think the example should be updated accordingly, so that getting started becomes easier.

**Comment by peter-ch** [comment]
The constructor now needs one more argument, an int, for the random seed. Have this be a hardcoded value like 0 (the run will be reproducible then) or the current time or something else. The documentation was updated.
