### ISSUE TITLE
Bugs: Incoherent bias neuron behavior

### ISSUE THREAD

**Issue by ydawei** [peter-ch/MultiNEAT#24]
I manually specified `DontUseBiasNeuron=True` in the parameter, but in[ `Genome::Mate(...)` ](https://github.com/peter-ch/MultiNEAT/blob/b1aa1e7180dcd419b3b39f8810c9238402c0638f/src/Genome.cpp#L2307-L2312)it still adds a bias neuron.

Also, the[ `NeuralNetwork::Input(..)` function](https://github.com/peter-ch/MultiNEAT/blob/b1aa1e7180dcd419b3b39f8810c9238402c0638f/src/NeuralNetwork.cpp#L592) ignores bias neuron and views the bias neuron as an input neuron.

**Comment by peter-ch** [comment]
Thanks, I'll take a look.

**Comment by peter-ch** [comment]
The problem in Genome::Mate() was fixed recently. NeuralNetwork::Input() is supposed to ignore the bias. At the point of activating the NN all inputs are treated equal. The bias isn't given a value of 1.0 automatically, the user has to supply it.
