### ISSUE TITLE
Genome::NeuronDepth function gets stuck in infinite recursion

### ISSUE THREAD

**Issue by jeteon** [peter-ch/MultiNEAT#59]
I have had a number of long running runs seemingly get stuck but with very high CPU usage. Today I tried to debug these and found that it's caused by a (_almost_) infinite recursive loop where the function `Genome::NeuronDepth` calls itself. This happens as a result to a call to the `Genome::NeuronDepth` function. I'm still yet to investigate further though so I can find a minimal reproduction case. I suspect that it may be due to a loop within the genome.

**Comment by peter-ch** [comment]
This happens when there is a loop in the network. Make sure there aren't any first, with HasLoops().

**Comment by jeteon** [comment]
Yeah, I eventually, figured that I can't have any recurrence and call the depth function. I was hoping it would still give me some indicator of the depth with loops broken/ignored but I guess there isn't really a sane way to do that. Thanks for replying.
