### ISSUE TITLE
Recurrent neural network

### ISSUE THREAD

**Issue by milan-rybar** [peter-ch/MultiNEAT#8]
Why do you define a forward link as that the From neuron has less or equal SplitY value than To neuron? (at Genome::Mutate_AddLink) That way, even with Parameters.RecurrentProb = 0, it creates links on the same layer, which results in cycles. Therefore, it always creates recurrent neural network. 

Is it a bug or does it have a purpose?

**Comment by peter-ch** [comment]
It's a bug, it needs a better method for doing this. I think I should add one "AllowCycles" parameter which will prevent cycles from appearing.

**Comment by peter-ch** [comment]
There is an AllowLoops parameter now that should fix this.
