### ISSUE TITLE
Seeding random number generator for parallelization

### ISSUE THREAD

**Issue by milan-rybar** [peter-ch/MultiNEAT#9]
Random number generator is initialized with time in seconds. When running more experiments in parallel, random generator returns the same values and results of these experiments are completely the same.

I am using C++11, so I change seeding from _time(0)_ to _std::chrono::system_clock::now().time_since_epoch().count())_ from _chrono_ header.
Nevertheless, you can find something similar in boost to obtain time in miliseconds.

**Comment by flajann2** [comment]
What I've done in similar circumstances is take random numbers from the master thread and used them as seeds to the slaves threads / processes. The benefit is that you get absolute reproducibility as well as good randomization.

**Comment by peter-ch** [comment]
I added a new parameter to the Population constructor for the random seed. I figured that one might not always need the seed to be random, for example when you want to reproduce an experiment, so I left this up to the users to decide.
